main/urls.py
from django.urls import path
from . import views
app_name = 'main'

urlpatterns = [
    path('Dashboard', views.view_dashboard, name='view-dashboard'),
    path('Dashboard/RefreshCPU', views.refresh_cpu, name='refresh-cpu'),
]

web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('', views.view_dashboard, name='view-homepage'),
    path('Main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/views.py
import requests
from django.http import JsonResponse
from django.shortcuts import render

from main.methods import get_processes_info


def view_dashboard(request):

    processes = get_processes_info()

    url = 'https://api.stackexchange.com/2.2/search?intitle=grafana&site=stackoverflow'
    response = requests.get(url).json()
    top10_views = sorted(response['items'], key=lambda d: d['view_count'], reverse=True)[:10]

    context = {
        'processes': processes,
        'top10_views': top10_views
    }

    return render(request, 'view_dashboard.html', context)

def refresh_cpu(request):

    processes = get_processes_info()
    data = {
        'processes': processes
    }
    return JsonResponse(data)

templates/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Python Web App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="icon" href="data:;base64,iVBORw0KGgo=">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Python Web App</a>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav"></ul>
            </div>
        </nav>
        <div class="flash_notif_out">
            <div class="flash_notif_in">
                <span id="notif-msg">
                    Scraping finished!
                </span>
            </div>
        </div>
        <div id="content-wrapper" class="content_wrapper">
            <div class="content container-fluid">
                {% block content %} {% endblock %}
            </div>
        </div>
    </body>
</html>

templates/view_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cpu_outer">
                    <h1>CPU Usage</h1>
                    <button id="refresh-cpu" class="btn btn-outline-info btn-sm pull-right m-2">Refresh</button>
                    <table id="cpu-usage-table" class="table cpu_usage_table">
                        <thead>
                            <tr>
                                <th>PID</th>
                                <th>Name</th>
                                <th>Cores</th>
                                <th>CPU Usage</th>
                                <th>Status</th>
                                <th>Memory Usage</th>
                                <th>Read</th>
                                <th>Write</th>
                                <th>Threads</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for process in processes %}
                            <tr>
                                <td>{{ process.pid }}</td>
                                <td>{{ process.name }}</td>
                                <td>{{ process.cores }}</td>
                                <td>{{ process.cpu_usage }}</td>
                                <td>{{ process.status }}</td>
                                <td>{{ process.memory_usage }}</td>
                                <td>{{ process.read_bytes }}</td>
                                <td>{{ process.read_bytes }}</td>
                                <td>{{ process.threads }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="top10_outer">
                    <h1>TOP 10 Topics with highest view_count</h1>
                    <ul class="list-group">
                        {% for list in top10_views %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{{ list.link }}" target=”_blank”>{{ list.link }}</a>
                            <span class="badge badge-primary badge-pill" style="color: black;">{{ list.view_count }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            function cpuStats(destroy){
                $('#cpu-usage-table').DataTable({
                    order: [[3, 'desc']],
                    scrollX: true,
                    searching: true,
                    pageLength: 10,
                    lengthMenu: [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
                    sortable: true,
                    responsive: true,
                    columns: [
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                        { "width": "11%" },
                    ],
                    language: {
                        searchPlaceholder: "Filter search",
                        search: "",
                    }
                });
            }
            cpuStats(false);
            $('#refresh-cpu').on('click', function(){
                $.ajax({
                    headers: { "X-CSRFToken": '{{ csrf_token }}' },
                    url : '{% url 'main:refresh-cpu' %}',
                    dataType: "json",
                    traditional: true,
                    data : {},
                    type : 'POST',
                    success : function(data){
                        $('#cpu-usage-table').DataTable({
                            order: [[3, 'desc']],
                            data: data.processes,
                            destroy: true,
                            scrollX: true,
                            searching: true,
                            pageLength: 10,
                            lengthMenu: [ [10, 25, 50, 100, -1], [10, 25, 50, 100, "All"] ],
                            sortable: true,
                            responsive: true,
                            columns: [
                                { "width": "11%", 'data': 'pid' },
                                { "width": "11%", 'data': 'name' },
                                { "width": "11%", 'data': 'cores' },
                                { "width": "11%", 'data': 'cpu_usage' },
                                { "width": "11%", 'data': 'status' },
                                { "width": "11%", 'data': 'memory_usage' },
                                { "width": "11%", 'data': 'read_bytes' },
                                { "width": "11%", 'data': 'write_bytes' },
                                { "width": "11%", 'data': 'threads' },
                            ],
                            language: {
                                searchPlaceholder: "Filter search",
                                search: "",
                            }
                        });
                    }
                });
            });
        });
    </script>
{% endblock %}